### ISSUE TITLE
VAC Detected

### ISSUE THREAD

**Issue by dontbestupid** [Deivison153/ProjectVanguardCSGOFree#1]
Project is detected since Valve added retaddr checks Feb. 2022

https://github.com/dretax/GarHal_CSGO/issues/109

_Original Sourcecode:_
https://github.com/dretax/GarHal_CSGO

_Credits to dretax_

![troll](https://user-images.githubusercontent.com/94144947/187025534-f2ec247d-5470-4064-ab62-b9b43335bd83.jpg)

**Comment by josealissonbr** [comment]
Thanks for sharing this with me, I'll try to learn ways around this.

**Comment by dretax** [comment]
Isn't this a pure paste of Garhal @josealissonbr

**Comment by Eurioin** [comment]
![image](https://user-images.githubusercontent.com/32771940/187379263-52b38185-e45b-4b47-8cbe-6d523383d597.png)

**Comment by josealissonbr** [comment]
> Isn't this a pure paste of Garhal @josealissonbr @dontbestupid @Deivison153 How do you even have the face to fucking blatantly paste, rename, and do not credit other people? No, you won't learn ways around that.

hi, I didn't even know about Garhal's existence when I was pasting this cheat, I made him by watching GuidedHacking tutorial videos. Don't accuse me of stealing codes from him or anything like that.

https://youtu.be/eumG222Efzs
https://youtu.be/Nl2PN7TvJZ4

I could never have given you credit for something here, as I didn't even know it existed, I only found out when some UC users told me about detection.

If you're upset because you didn't get the credits, I recommend talking to YouTube channels, as they use your code without letting you know it's yours.

I hope I have clarified this question and that we can live together in this vast world

**Comment by Deivison153** [comment]
> Isn't this a pure paste of Garhal @josealissonbr @dontbestupid @Deivison153 How do you even have the face to fucking blatantly paste, rename, and do not credit other people? No, you won't learn ways around that.


As a @josealissonbr metioned before, there are 2 possibilities, either GH copied it from you or you copied it from GH, the most obvious answer is that you also copied it from GH, if not that happened a very big coincidence for the two of you code to have been very similar and equal, so stop saying that we copied in plain view and didn't give credit to anyone since on the internet anyone can do it just by watching a damn video. LMAO

**Comment by Life45** [comment]
> > Isn't this a pure paste of Garhal @josealissonbr @dontbestupid @Deivison153 How do you even have the face to fucking blatantly paste, rename, and do not credit other people? No, you won't learn ways around that.
> 
> As a @josealissonbr metioned before, there are 2 possibilities, either GH copied it from you or you copied it from GH, the most obvious answer is that you also copied it from GH, if not that happened a very big coincidence for the two of you code to have been very similar and equal, so stop saying that we copied in plain view and didn't give credit to anyone since on the internet anyone can do it just by watching a damn video. LMAO

The video you sent literally starts with "Hello guys, my name is Dretax", he is the author of video as well lmao

**Comment by dretax** [comment]
> > Isn't this a pure paste of Garhal @josealissonbr @dontbestupid @Deivison153 How do you even have the face to fucking blatantly paste, rename, and do not credit other people? No, you won't learn ways around that.
> 
> hi, I didn't even know about Garhal's existence when I was pasting this cheat, I made him by watching GuidedHacking tutorial videos. Don't accuse me of stealing codes from him or anything like that.
> 
> https://youtu.be/eumG222Efzs https://youtu.be/Nl2PN7TvJZ4
> 
> I could never have given you credit for something here, as I didn't even know it existed, I only found out when some UC users told me about detection.
> 
> If you're upset because you didn't get the credits, I recommend talking to YouTube channels, as they use your code without letting you know it's yours.
> 
> I hope I have clarified this question and that we can live together in this vast world

That's ME in the tutorial. I made it with all my passion towards GH because i consider myself as a family member there and admire @GH-Rake 's work. 
Every single author of Garhal is mentioned there for a reason.


> > Isn't this a pure paste of Garhal @josealissonbr @dontbestupid @Deivison153 How do you even have the face to fucking blatantly paste, rename, and do not credit other people? No, you won't learn ways around that.
> 
> As a @josealissonbr metioned before, there are 2 possibilities, either GH copied it from you or you copied it from GH, the most obvious answer is that you also copied it from GH, if not that happened a very big coincidence for the two of you code to have been very similar and equal, so stop saying that we copied in plain view and didn't give credit to anyone since on the internet anyone can do it just by watching a damn video. LMAO

Are you joking? The WHOLE setup of the project is the same code as mine. How do you even have the face to deny all of this?

**Comment by josealissonbr** [comment]
> > > Isn't this a pure paste of Garhal @josealissonbr @dontbestupid @Deivison153 How do you even have the face to fucking blatantly paste, rename, and do not credit other people? No, you won't learn ways around that.
> > 
> > 
> > hi, I didn't even know about Garhal's existence when I was pasting this cheat, I made him by watching GuidedHacking tutorial videos. Don't accuse me of stealing codes from him or anything like that.
> > https://youtu.be/eumG222Efzs https://youtu.be/Nl2PN7TvJZ4
> > I could never have given you credit for something here, as I didn't even know it existed, I only found out when some UC users told me about detection.
> > If you're upset because you didn't get the credits, I recommend talking to YouTube channels, as they use your code without letting you know it's yours.
> > I hope I have clarified this question and that we can live together in this vast world
> 
> That's ME in the tutorial. I made it with all my passion towards GH because i consider myself as a family member there and admire @GH-Rake 's work. Every single author of Garhal is mentioned there for a reason.
> 
> > > Isn't this a pure paste of Garhal @josealissonbr @dontbestupid @Deivison153 How do you even have the face to fucking blatantly paste, rename, and do not credit other people? No, you won't learn ways around that.
> > 
> > 
> > As a @josealissonbr metioned before, there are 2 possibilities, either GH copied it from you or you copied it from GH, the most obvious answer is that you also copied it from GH, if not that happened a very big coincidence for the two of you code to have been very similar and equal, so stop saying that we copied in plain view and didn't give credit to anyone since on the internet anyone can do it just by watching a damn video. LMAO
> 
> Are you joking? The WHOLE setup of the project is the same code as mine. How do you even have the face to deny all of this?

As I said above, we don't copy from your github repository, we only watch the videos from the GuidedHacking channel, and I didn't pay attention to who recorded the video.
Friend I don't gain anything or lose anything telling you that I didn't copy from your Github repository, I'm telling the truth.

If I had copied it from your repository, I would obviously have mentioned it.

As I mentioned above, I just pasted codes from the video mentioned above (GH channel), and also from Cazz's channel (Aimbot).

I really appreciate you making the video, it really opened my mind on the kernel.

**Comment by Eurioin** [comment]
> > Isn't this a pure paste of Garhal @josealissonbr @dontbestupid @Deivison153 How do you even have the face to fucking blatantly paste, rename, and do not credit other people? No, you won't learn ways around that.
> 
> As a @josealissonbr metioned before, there are 2 possibilities, either GH copied it from you or you copied it from GH, the most obvious answer is that you also copied it from GH, if not that happened a very big coincidence for the two of you code to have been very similar and equal, so stop saying that we copied in plain view and didn't give credit to anyone since on the internet anyone can do it just by watching a damn video. LMAO

So god damn blind and deaf... First of all, if you copy a code and publish it, at least take time and understand wtf is going on behind it to be able to make significant changes in it before blatantly publicating it to anywhere (yep, this exists and is called plagarism, welcome -.-). After getting called out for it like a fucking braindead moron, the least thing you can do is apologize to the author and make the repo private (or completly remove it)... Get your shit together... No problem in learning, the problem is in blatantly publicating and shit-defensing everything about it.

What could have happened hear is that the music was so loud that you were just looking at images of the muted video not taking a single fuck about the actual content behind it, which is even more upsetting.

When Garhal turned up on the UC comments, you guys didn't care about it, even when the original author of the code and project appeared here, you guys just started denying even your life. At least dont be that fucking stupid to copy a code and hope noone notices it...

**Comment by dretax** [comment]
Fine, take It your way, I have no problems with learning, but claiming something "as-is" "yours" like you did on UC is still completely unacceptable from my, and probably other people's ends.
Glad atleast I could teach a bare slice of the content to you.

**Comment by josealissonbr** [comment]
> > > Não é esta uma pasta pura de Garhal@josealissonbr @dontbestupid @Deivison153Como você ainda tem cara de descaradamente colar, renomear e não creditar outras pessoas? Não, você não vai aprender maneiras de contornar isso.
> > 
> > 
> > Como um@josealissonbrmencionado antes, existem 2 possibilidades, ou o GH copiou de você ou você copiou do GH, a resposta mais óbvia é que você também copiou do GH, se não isso aconteceu uma coincidência muito grande para vocês dois codificarem ficou muito parecido e igual, então pare de dizer que copiamos à vista de todos e não demos crédito a ninguém, pois na internet qualquer um pode fazer isso apenas assistindo a um vídeo maldito. rindo muito
> 
> Então, malditos cegos e surdos... Em primeiro lugar, se você copiar um código e publicá-lo, pelo menos reserve um tempo e entenda o que está acontecendo por trás dele para poder fazer mudanças significativas nele antes de publicá-lo descaradamente em qualquer lugar ( sim, isso existe e é chamado de plágio, bem-vindo -.-). Depois de ser chamado por isso como um idiota sem cérebro, o mínimo que você pode fazer é se desculpar com o autor e tornar o repositório privado (ou removê-lo completamente)... problema está em descaradamente publicar e defender tudo sobre isso.
> 
> O que poderia ter acontecido ao ouvir é que a música estava tão alta que você estava apenas olhando as imagens do vídeo mudo sem se importar com o conteúdo real por trás dele, o que é ainda mais perturbador.
> 
> Quando Garhal apareceu nos comentários da UC, vocês não se importaram com isso, mesmo quando o autor original do código e do projeto apareceu aqui, vocês começaram a negar até mesmo sua vida. Pelo menos não seja tão estúpido para copiar um código e esperar que ninguém perceba...
Dude you are really being an idiot in all your sentences, but you are correct for the most part.

**Comment by josealissonbr** [comment]
> Fine, take It your way, I have no problems with learning, but claiming something "as-is" "yours" like you did on UC is still completely unacceptable from my, and probably other people's ends. Glad atleast I could teach a bare slice of the content to you.

ok, it will be done
